name: Read
description: Looks up books information given an issue with the title of an ISBN.
runs:
  using: node16
  main: dist/index.js

inputs:
  readFileName:
    description: The file where you want to save your books.
    default: _data/read.json
  providers:
    description: Specify the [ISBN providers](https://github.com/palmerabollo/node-isbn#setting-backend-providers) that you want to use, in the order you need them to be invoked. If setting more than one provider, separate each with a comma.
